"""add reply_templates table

Revision ID: 69358403a2aa
Revises: 7f3afd3b070f
Create Date: 2026-09-04 07:27:46.964901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69358403a2aa"
down_revision: str | Sequence[str] | None = "7f3afd3b070f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reply_templates",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("scenario", sa.String(length=255), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=255), nullable=False),
        sa.Column("variables", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("createdAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scenario", "locale", name="uq_reply_templates_scenario_locale"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply_templates")
    # ### end Alembic commands ###
